version: "3.7"
services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: >
      -c ssl=on
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
      -c logging_collector=on
      -c log_directory=/var/log/postgresql
      -c log_filename=postgresql.log
      -c log_statement=all
    volumes:
      - ./volumes/var/lib/postgresql:/var/lib/postgresql
      - ./volumes/var/log/postgresql:/var/log/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} --dbname ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 12
    networks:
      - pgdata

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations", 
      "-database", "postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}?sslmode=disable",
      "up"
      ]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - pgdata

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_PORT=${API_PORT}
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      DB_URL: "postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}?sslmode=disable"
      LOG_LEVEL: ${LOG_LEVEL}
      API_PORT: ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - pgdata

networks:
  pgdata: {}
